services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: udlf-web-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_URL_API_LOCAL=http://localhost:8080
      - HOST_UDLF_PATH=${HOST_UDLF_PATH}
    env_file:
      - .env
    restart: on-failure