services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: udlf-web-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    restart: on-failure
